OBJ = agregarSegundo.o
CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wpedantic

programa: $(OBJ)
        $(CXX) $(CXXFLAGS) agregarSegundo.o -o agregarSegundo 

clean:
        rm -rf *.o *.txt 
        rm agregarSegundo
