OBJ = numbers_in_an_interval.o
CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wpedantic

programa: $(OBJ)
        $(CXX) $(CXXFLAGS) numbers_in_an_interval.o -o numbers_in_an_interval 

clean:
        rm -rf *.o *.txt 
        rm numbers_in_an_interval
