OBJ = letras_mayusculas_minus.o
CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wpedantic

programa: $(OBJ)
        $(CXX) $(CXXFLAGS) letras_mayusculas_minus.o -o letras_mayusculas_minus 

clean:
        rm -rf *.o *.txt 
        rm letras_mayusculas_minus